<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '50%' => '50% уверенность',
    '50% intevral must be inside 90%' => 'Интервал 50%-уверенности должен быть внутри 90%',
    '90%' => '90% уверенность',
    'Answer' => 'Ответ',
    'Answers Count' => 'Вопросов отвечено',
    'Brain Calibrator' => 'Калибровка мозга',
    'Congratulations! Questions is over, you are answered it all!' => 'Поздравляем! Ты прошёл игру!',
    'Date Approved' => 'Дата принятия',
    'Date Submitted' => 'Дата отправки',
    'End must be more than start' => 'Конец интервала должен быть больше чем начало',
    'Fifty Count' => 'Правильно отвечено для 50% вероятности',
    'Fifty End' => 'Конец интервала 50%-уверенности',
    'Fifty Start' => 'Начало интервала 50%-уверенности',
    'From' => 'От',
    'Game over' => 'Игра окончена',
    'ID' => 'ID',
    'Is Correct' => 'Правильность ответа',
    'Login' => 'Вход',
    'Login with VK' => 'Войти через VK',
    'Name' => 'Имя',
    'Next question' => 'Следующий вопрос',
    'Ninety Count' => 'Правильно отвечено для 90% уверенности',
    'Ninety End' => 'Конец интервала 90%-уверенности',
    'Ninety Start' => 'Начало интервала 90%-уверенности',
    'No more questions' => 'Больше нет вопросов',
    'Question ID' => 'ID вопроса',
    'Registration error' => 'Ошибка при регистрации',
    'Reset' => 'Сбросить',
    'Score' => 'Рейтинг',
    'Search' => 'Поиск',
    'Send answer' => 'Отправить ответ',
    'Skip question' => 'Пропустить вопрос',
    'Source ID' => 'ID источника',
    'Source Type' => 'Тип источника',
    'Text' => 'Текст',
    'The requested page does not exist.' => 'Запрошенная страница не существует',
    'To' => 'До',
    'User ID' => 'ID игрока',
    'Users' => 'Игроки',
    'Users rating' => 'Рейтинг игроков',
    'You answered' => 'Вы ответили',
    'You are answered this question' => 'Вы ответили на этот вопрос',
    'You have not access to view this page' => 'У вас нет прав на просмотр этой страницы',
    'Your score' => 'Ваш рейтинг',
];
