<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '50%' => '50% уверенность',
    '50% intevral must be inside 90%' => 'Интервал 50%-уверенности должен быть внутри 90%',
    '90%' => '90% уверенность',
    'Administrator' => 'Администратор',
    'Answer' => 'Ответ',
    'Answer a question' => 'Ответить на вопрос',
    'Answers Count' => 'Вопросов отвечено',
    'Approve' => 'Принять',
    'Are you sure you want to delete this item?' => 'Вы действительно хотите удалить?',
    'Brain Calibrator' => 'Калибровка мозга',
    'Congratulations! Questions is over, you are answered it all!' => 'Поздравляем!<br> Ты прошёл игру!',
    'Create' => 'Создать',
    'Create Question' => 'Создание вопроса',
    'Date Approved' => 'Дата принятия',
    'Date Submitted' => 'Дата отправки',
    'Delete' => 'Удалить',
    'Edit' => 'Редактировать',
    'End must be more than start' => 'Конец интервала должен быть больше чем начало',
    'Female' => 'Женский',
    'Fifty Count' => 'Попаданий в 50%-диапазон',
    'Fifty End' => 'Конец интервала 50%-уверенности',
    'Fifty Start' => 'Начало интервала 50%-уверенности',
    'Fifty diapasons looking good' => 'Диапазоны 50%-уверенности выглядят неплохо',
    'Fifty diapasons too big' => 'Диапазоны 50%-уверенности слишком широкие',
    'Fifty diapasons too small' => 'Диапазоны 50%-уверенности слишком узкие',
    'From' => 'От',
    'From <strong>{0}</strong> to <strong>{1}</strong>' => 'От <strong>{0}</strong> до <strong>{1}</strong>',
    'Game over' => 'Игра окончена',
    'Gender' => 'Пол',
    'ID' => 'ID',
    'Incorrect' => 'Нет попадания',
    'Invalid auth key' => 'Неправильный авторизационный ключ',
    'Is Correct' => 'Правильность ответа',
    'Login' => 'Вход',
    'Login with VK' => 'Войти через VK',
    'Male' => 'Мужской',
    'Moderator' => 'Модератор',
    'Name' => 'Имя',
    'New questions' => 'Новые вопросы',
    'Next question' => 'Следующий вопрос',
    'Ninety Count' => 'Попаданий в 90%-диапазон',
    'Ninety End' => 'Конец интервала 90%-уверенности',
    'Ninety Start' => 'Начало интервала 90%-уверенности',
    'Ninety diapasons looking good' => 'Диапазоны 90%-уверенности выглядят неплохо',
    'Ninety diapasons too big' => 'Диапазоны 90%-уверенности слишком широкие',
    'Ninety diapasons too small' => 'Диапазоны 90%-уверенности слишком узкие',
    'Photo' => 'Фото',
    'Please contact us if you think this is a server error. Thank you.' => 'Пожалуйста, сообщите <a href="https://vk.com/write220508153" target="_blank">мне</a> если это ошибка сервера. Заранее спасибо.',
    'Question' => 'Вопрос',
    'Question ID' => 'ID вопроса',
    'Questions' => 'Вопросы',
    'Questions Count' => 'Количество вопросов',
    'Registration error' => 'Ошибка при регистрации',
    'Reset' => 'Сбросить',
    'Role' => 'Роль',
    'Score' => 'Рейтинг',
    'Search' => 'Поиск',
    'Send answer' => 'Отправить ответ',
    'Skip question' => 'Пропустить вопрос',
    'Source' => 'Источник',
    'Source ID' => 'ID источника',
    'Source Type' => 'Тип источника',
    'Submit' => 'Отправить',
    'Submit question' => 'Отправить вопрос',
    'Submitter ID' => 'ID Отправителя',
    'Suggest Question' => 'Предложить вопрос',
    'Text' => 'Текст',
    'The above error occurred while the Web server was processing your request.' => 'Во время обработки вашего запроса произошла ошибка.',
    'The requested page does not exist.' => 'Запрошенная страница не существует',
    'There`s no more questions for you.' => 'В игре больше нет неотвеченных вопросов для тебя.',
    'To' => 'До',
    'Unknown gender' => 'Неизвестный пол',
    'Update' => 'Обновить',
    'Update {modelClass}: ' => 'Обновить {modelClass}',
    'User' => 'Игрок',
    'User ID' => 'ID игрока',
    'Users' => 'Игроки',
    'Users rating' => 'Рейтинг игроков',
    'You answered' => 'Вы ответили',
    'You are answered this question' => 'Вы ответили на этот вопрос',
    'You can suggest your own question for others players and share this app to friends.' => 'Ты можешь предложить свой вопрос другим игрокам и рассказать об приложении друзьям, чтобы они тоже откалибровали свой мозг.',
    'You have not access to view this page' => 'У вас нет прав на просмотр этой страницы',
    'Your score' => 'Ваш рейтинг',
];
